<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 20 May 2025 14:01:43 +0000
 */

$conf['title'] = 'Tabulify - Growing data proficiency of the world';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['toptoclevel'] = '2';
$conf['tocminheads'] = '1';
$conf['useheading'] = '1';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['indexdelay'] = 0;
$conf['plugin']['combo']['prismTheme'] = 'prism';
$conf['plugin']['combo']['mandatoryQualityRules'] = 'internal_backlinks_min,internal_links_min,words_min';
$conf['plugin']['combo']['pageUrlType'] = 'slug';
$conf['plugin']['combo']['enableFrontMatterOnSubmit'] = 1;
$conf['plugin']['combo']['primaryColor'] = '#326e32';
$conf['plugin']['combo']['privateRailbar'] = 1;
$conf['plugin']['googleanalytics']['GTAGID'] = 'G-4XWKFHYS5D';
$conf['plugin']['googletagmanager']['GTMID'] = 'GTM-MD83VQ8';
